pin_run_as_build:
  zeromq:
    # zeromq on Windows requires strict pinning
    min_pin: x.x.x  # [win]
    max_pin: x.x.x  # [win]
    max_pin: x.x    # [not win]

cxx_compiler:  # [win]
  - vs2022  # [win]