{% set version = "27.1.0" %}
{% set name = "pyzmq" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # We use the pypi URL as it includes the prepared Cython files.
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ac0765e3d44455adb6ddbf4417dcce460fc40a05978c08efdf2948072f6db540

build:
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - make  # [not win]
    - pkg-config 0.29.2  # [not win]
    - ninja-base  # [win]
  host:
    - pip
    - python
    - cffi  # [python_impl == 'pypy']
    - cython >=3.1.0  # [python_impl != 'pypy']
    - packaging
    - scikit-build-core >=0.10
    - zeromq 4.3.5
  run:
    - python
    - cffi  # [python_impl == 'pypy']
    - zeromq # constraint through run_exports

{% set ignore_tests = "" %}
# Random exception on win CI
{% set ignore_tests = " --ignore=tests\test_zmqstream.py" %}  # [win]
# test_process_teardown: assert proc.exitcode == 0, f"Python process died with code {proc.exitcode}"
{% set tests_to_skip = "test_show_builders" %}

test:
  source_files:
    - pyproject.toml
    - pytest.ini
    - tests
  imports:
    - zmq
    - zmq._future
    - zmq._typing
    - zmq.asyncio
    - zmq.auth
    - zmq.backend
    - zmq.constants
    - zmq.decorators
    - zmq.devices
    - zmq.error
    - zmq.eventloop
    - zmq.green
    - zmq.log
    - zmq.ssh.tunnel
    - zmq.sugar
    - zmq.utils
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-rerunfailures
    - tornado
    - gevent
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest tests -k "not ({{ tests_to_skip }})" {{ ignore_tests }}

about:
  home: https://github.com/zeromq/pyzmq
  summary: Python bindings for zeromq
  license: BSD-3-Clause
  license_file: LICENSE.md
  license_family: BSD
  description: |
    PyZMQ contains Python bindings for 0MQ. 0MQ is a lightweight and fast
    messaging implementation.
  doc_source_url: https://github.com/zeromq/pyzmq/blob/master/docs/source/index.rst
  dev_url: https://github.com/zeromq/pyzmq

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - msarahan
    - pelson
    - SylvainCorlay
    - JohanMabille
    - ocefpaf
    - mingwandroid
    - chenghlee