{% set version = "26.2.0" %}

package:
  name: pyzmq
  version: {{ version }}

source:
  # We use the pypi URL as it includes the prepared Cython files.
  url: https://pypi.io/packages/source/p/pyzmq/pyzmq-{{ version }}.tar.gz
  sha256: 070672c258581c8e4f640b5159297580a9974b026043bd4ab0470be9ed324f1f

build:
  number: 0
  skip: True  # [py<37]

requirements:
  build:
    - pkg-config 0.29.2  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - make  # [not win]
    - ninja-base # [win]
  host:
    - python
    - packaging
    - pip
    - scikit-build-core
    - cython >=3.0.0
    - zeromq 4.3.5
  run:
    - python
    - zeromq >=4.3.5,<4.4.0a0

test:
  source_files:
    - pyproject.toml
    - pytest.ini
    - tests
  imports:
    - zmq
    - zmq.backend.cython
    - zmq.devices.monitoredqueue
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-rerunfailures
    - tornado
  commands:
    - pip check
    - pytest -m "not new_console and not wheel and not large" -k "not test_process_teardown"

about:
  home: https://github.com/zeromq/pyzmq
  summary: Python bindings for zeromq
  license: BSD-3-Clause
  license_file: LICENSE.md
  license_family: BSD
  description: |
    PyZMQ contains Python bindings for 0MQ. 0MQ is a lightweight and fast
    messaging implementation.
  doc_source_url: https://github.com/zeromq/pyzmq/blob/master/docs/source/index.rst
  dev_url: https://github.com/zeromq/pyzmq

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - msarahan
    - pelson
    - SylvainCorlay
    - JohanMabille
    - ocefpaf
    - mingwandroid
    - chenghlee
