{% set version = "27.2.0" %}
{% set name = "pyzmq" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # We use the pypi URL as it includes the prepared Cython files.
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54d4259d1bfae24ecdb5ca79f7acc2eac6c286a02d6a0ae617797cb45f0726d3

build:
  number: 0
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - make  # [not win]
    - pkg-config 0.29.2  # [not win]
  host:
    - pip
    - python
    - cffi  # [python_impl == 'pypy']
    - cython >=3.0.0  # [python_impl != 'pypy']
    - packaging
    - scikit-build-core >=0.10
    - zeromq 4.3.5
  run:
    - python
    - cffi  # [python_impl == 'pypy']
    - zeromq  # constraint through run_exports

{% set tests_to_skip = "" %}
# CI issue: zmq.error.ZMQError: Socket operation on non-socket
# Works fine locally on the Docker instance.
{% set tests_to_skip = tests_to_skip + " --ignore=tests/test_log.py" %}  # [linux64]
# Flaky on x64 Linux with Python 3.14
# E subprocess.CalledProcessError: Command 
{% set tests_to_skip = tests_to_skip + " --deselect=tests/test_curve_keygen.py::test_curve_keygen_secret" %}  # [linux64 and py>=314]
# E AssertionError: Python process died with code 1
# E where 1 = <ProcessForTeardownTest name='ProcessForTeardownTest-1' pid=74778 parent=74770 stopped exitcode=1>.exitcode
{% set tests_to_skip = tests_to_skip + " --deselect=tests/test_asyncio.py::test_process_teardown" %}

test:
  source_files:
    - pyproject.toml
    - pytest.ini
    - tests
  imports:
    - zmq
    - zmq._future
    - zmq._typing
    - zmq.asyncio
    - zmq.auth
    - zmq.backend
    - zmq.constants
    - zmq.decorators
    - zmq.devices
    - zmq.error
    - zmq.eventloop
    - zmq.green
    - zmq.log
    - zmq.ssh.tunnel
    - zmq.sugar
    - zmq.utils
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-rerunfailures
    - tornado
    - gevent
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest tests {{ tests_to_skip }}

about:
  home: https://github.com/zeromq/pyzmq
  summary: Python bindings for zeromq
  license: BSD-3-Clause
  license_file: LICENSE.md
  license_family: BSD
  description: |
    PyZMQ contains Python bindings for 0MQ. 0MQ is a lightweight and fast
    messaging implementation.
  doc_url: https://pyzmq.readthedocs.io
  dev_url: https://github.com/zeromq/pyzmq

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - msarahan
    - pelson
    - SylvainCorlay
    - JohanMabille
    - ocefpaf
    - mingwandroid
    - chenghlee
