{% set version = "24.0.1" %}

package:
  name: pyzmq
  version: {{ version }}

source:
  # We use the pypi URL as it includes the prepared Cython files.
  url: https://pypi.io/packages/source/p/pyzmq/pyzmq-{{ version }}.tar.gz
  sha256: 216f5d7dbb67166759e59b0479bca82b8acf9bed6015b526b8eb10143fb08e77

build:
  number: 0
  skip: True  # [py<36]

requirements:
  build:
    - pkg-config 0.29.2  # [not win]
    - {{ compiler('c') }}
  host:
    - python
    - packaging
    - pip
    - setuptools
    - wheel
    - cython >=0.29.35,<3
    - zeromq 4.3.5
  run:
    - python
    - zeromq >=4.3.5,<4.4.0a0

test:
  imports:
    - zmq
    - zmq.backend.cython.socket
    - zmq.backend.cython.utils
    - zmq.devices.monitoredqueue
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - py.test --pyargs zmq.tests.test_socket

about:
  home: https://github.com/zeromq/pyzmq
  summary: Python bindings for zeromq
  license: BSD-3-Clause AND LGPL-3.0-or-later
  license_file:
     - LICENSE.BSD
     - LICENSE.LESSER
  license_family: BSD
  description: |
    PyZMQ contains Python bindings for 0MQ. 0MQ is a lightweight and fast
    messaging implementation.
  doc_source_url: https://github.com/zeromq/pyzmq/blob/master/docs/source/index.rst
  dev_url: https://github.com/zeromq/pyzmq

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - msarahan
    - pelson
    - SylvainCorlay
    - JohanMabille
    - ocefpaf
    - mingwandroid
    - chenghlee
