travis:
  secure:
    BINSTAR_TOKEN: b2dkKust0rNDEmiIwVYHbvS2Z24FGK4oP8E5pPXaCdY8rhUcCyqkp6paAimnI2uwNRVldQOwwKOnIHCIAm6GsgACmr8GeMsw4+FY18vxzlm2e1GMviRlV0iOfr1irF+YwFZq8UvnqyLpG2r3Xml5/OUwfHFt0CEUJBF5Amgdx6wuCzl0RB1YeQp+GQPMlAbseWUmq+jKXw9fFUbh2x7LAPndNF5gM4Te6huw7ArSLtYDAP7wQLMS1ApAE7vaywav6z7vbkItqiFJoyAvUZLoPxJcZ2B6CIdqP05woci7jHDi4+9QMmjSZ5vO+JqpVGfBcUFGZDG2E2TbP1q/n9vvWpYXdP3+dfRlsYbigJfpaRhVUzz5VoV0IHd1o1CeJ/eBpTVxSVwLmwONwnHlUPZgXHGd9wJg42cxxeTLUv6JaTPRjb7vVXUYI0o/02yo3RnVAUwSPGldAY9xWue5Y/t7UOjb2HJTHaZmNG0JLQvh3jgsRV5pNwD8f1WYj2cnf/AsyBEhWNjhIjMBqJe5s8WB6jR5WhnshzgFnIPoOlE9O+wH0F0b0NsgMXWtTHXHAD+zDNvjGf4T2EMHf1pTS+Y94+fUCx3NGcmDOdNWCIJDA/5M88rkVzEsQrVWA4PvRZNuGFECHvTUUCUfMh9QqfJWPgJKSIXGQAUXyJwLAQN1rpo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
