travis:
  secure:
    BINSTAR_TOKEN: QarOw0hXPAQ5FEQ0/Jvm2xIH1Rds9coqmlzb/eMy6cExeyMIQASD/CjxybKNOz3/Br/qVzghvazrHxtkVrMEUcBNh59dTQ+m5XMl9AcUvwdws2wQ+DjG35I5uRXtB+PGxBH+j/TSeD4GUUhzcbfKc7ywYBeQS7/s+xGAY+fgFk5HmwZGSeR6grpLcU1Nt0Fe42H2UmxmMCg/xpLwg0vhgftIUhmn1LrpHWncNd14eCqvI3FU87qQ1BXJmsrdSMY8y8GEq7dMYF5/Lj0Qhs/qjyqWW9fttG/d3ps5O7Vk4a6sxVTZpEMNv2ZTTNZ4UKlt0tMIMNcfH3CqOfry++YgbQrz8nVkJdJpIWrB+Smol4Ffu16j7m+EoJXS8A2XRfjPp5WMHjkghhf9SXD6fwF9bw/0OpOKgq4DB4AjLxnMdfXWoZ0FXEunmw2Y1bZIf7tN33+3vPK93zt6GFJimY8SVia519lgeS4cuwsL3muRB6okWcbQSUrnK85QLJ3JRAx9aH0Q4KUPDCjtN31iObDO/prrQTlCusPSUHZjpG1aapWgUGF7+W6HpqkUWWndKWfNi+4xwt7vg0Yw0woWMq8lFGrATjEd9u4u5iuY6WUjardjX0sag1NcTOTK39qsLBhV+N2aw629dd2DCV0OqWP5p0GER756m4Q61ZW9nZbOrDs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
